//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://www.openoandm.org/ws-isbm/", ClrNamespace = "www.openoandm.org.wsisbm")]
namespace OpenMSM.Web.ServiceDefinitions
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.openoandm.org/ws-isbm/", ConfigurationName = "ChannelManagementService")]
    public interface IChannelManagementService
    {

        // CODEGEN: Parameter 'SecurityToken' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/CreateChannel", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(www.openoandm.org.wsisbm.ChannelFault), Action = "http://www.openoandm.org/ws-isbm/CreateChannel", Name = "ChannelFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        CreateChannelResponse CreateChannel(CreateChannelRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/CreateChannel", ReplyAction = "*")]
        System.Threading.Tasks.Task<CreateChannelResponse> CreateChannelAsync(CreateChannelRequest request);

        // CODEGEN: Parameter 'SecurityToken' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/AddSecurityTokens", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(www.openoandm.org.wsisbm.ChannelFault), Action = "http://www.openoandm.org/ws-isbm/AddSecurityTokens", Name = "ChannelFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        AddSecurityTokensResponse AddSecurityTokens(AddSecurityTokensRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/AddSecurityTokens", ReplyAction = "*")]
        System.Threading.Tasks.Task<AddSecurityTokensResponse> AddSecurityTokensAsync(AddSecurityTokensRequest request);

        // CODEGEN: Parameter 'SecurityToken' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/RemoveSecurityTokens", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(www.openoandm.org.wsisbm.ChannelFault), Action = "http://www.openoandm.org/ws-isbm/RemoveSecurityTokens", Name = "ChannelFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(www.openoandm.org.wsisbm.SecurityTokenFault), Action = "http://www.openoandm.org/ws-isbm/RemoveSecurityTokens", Name = "SecurityTokenFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        RemoveSecurityTokensResponse RemoveSecurityTokens(RemoveSecurityTokensRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/RemoveSecurityTokens", ReplyAction = "*")]
        System.Threading.Tasks.Task<RemoveSecurityTokensResponse> RemoveSecurityTokensAsync(RemoveSecurityTokensRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/DeleteChannel", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(www.openoandm.org.wsisbm.ChannelFault), Action = "http://www.openoandm.org/ws-isbm/DeleteChannel", Name = "ChannelFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void DeleteChannel(string ChannelURI);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/DeleteChannel", ReplyAction = "*")]
        System.Threading.Tasks.Task DeleteChannelAsync(string ChannelURI);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/GetChannel", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(www.openoandm.org.wsisbm.ChannelFault), Action = "http://www.openoandm.org/ws-isbm/GetChannel", Name = "ChannelFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "Channel")]
        Channel GetChannel(string ChannelURI);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/GetChannel", ReplyAction = "*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "Channel")]
        System.Threading.Tasks.Task<Channel> GetChannelAsync(string ChannelURI);

        // CODEGEN: Parameter 'Channel' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/GetChannels", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "Channel")]
        GetChannelsResponse GetChannels(GetChannelsRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/GetChannels", ReplyAction = "*")]
        System.Threading.Tasks.Task<GetChannelsResponse> GetChannelsAsync(GetChannelsRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.openoandm.org/ws-isbm/")]
    public enum ChannelType
    {

        /// <remarks/>
        Publication,

        /// <remarks/>
        Request,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "CreateChannel", WrapperNamespace = "http://www.openoandm.org/ws-isbm/", IsWrapped = true)]
    public partial class CreateChannelRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openoandm.org/ws-isbm/", Order = 0)]
        public string ChannelURI;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openoandm.org/ws-isbm/", Order = 1)]
        public ChannelType ChannelType;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openoandm.org/ws-isbm/", Order = 2)]
        public string ChannelDescription;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openoandm.org/ws-isbm/", Order = 3)]
        [System.Xml.Serialization.XmlElementAttribute("SecurityToken")]
        public System.Xml.XmlElement[] SecurityToken;

        public CreateChannelRequest()
        {
        }

        public CreateChannelRequest(string ChannelURI, ChannelType ChannelType, string ChannelDescription, System.Xml.XmlElement[] SecurityToken)
        {
            this.ChannelURI = ChannelURI;
            this.ChannelType = ChannelType;
            this.ChannelDescription = ChannelDescription;
            this.SecurityToken = SecurityToken;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "CreateChannelResponse", WrapperNamespace = "http://www.openoandm.org/ws-isbm/", IsWrapped = true)]
    public partial class CreateChannelResponse
    {
        public CreateChannelResponse()
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "AddSecurityTokens", WrapperNamespace = "http://www.openoandm.org/ws-isbm/", IsWrapped = true)]
    public partial class AddSecurityTokensRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openoandm.org/ws-isbm/", Order = 0)]
        public string ChannelURI;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openoandm.org/ws-isbm/", Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute("SecurityToken")]
        public System.Xml.XmlElement[] SecurityToken;

        public AddSecurityTokensRequest()
        {
        }

        public AddSecurityTokensRequest(string ChannelURI, System.Xml.XmlElement[] SecurityToken)
        {
            this.ChannelURI = ChannelURI;
            this.SecurityToken = SecurityToken;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "AddSecurityTokensResponse", WrapperNamespace = "http://www.openoandm.org/ws-isbm/", IsWrapped = true)]
    public partial class AddSecurityTokensResponse
    {

        public AddSecurityTokensResponse()
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "RemoveSecurityTokens", WrapperNamespace = "http://www.openoandm.org/ws-isbm/", IsWrapped = true)]
    public partial class RemoveSecurityTokensRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openoandm.org/ws-isbm/", Order = 0)]
        public string ChannelURI;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openoandm.org/ws-isbm/", Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute("SecurityToken")]
        public System.Xml.XmlElement[] SecurityToken;

        public RemoveSecurityTokensRequest()
        {
        }

        public RemoveSecurityTokensRequest(string ChannelURI, System.Xml.XmlElement[] SecurityToken)
        {
            this.ChannelURI = ChannelURI;
            this.SecurityToken = SecurityToken;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "RemoveSecurityTokensResponse", WrapperNamespace = "http://www.openoandm.org/ws-isbm/", IsWrapped = true)]
    public partial class RemoveSecurityTokensResponse
    {

        public RemoveSecurityTokensResponse()
        {
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.openoandm.org/ws-isbm/")]
    public partial class Channel
    {

        private string channelURIField;

        private ChannelType channelTypeField;

        private string channelDescriptionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string ChannelURI
        {
            get
            {
                return this.channelURIField;
            }
            set
            {
                this.channelURIField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public ChannelType ChannelType
        {
            get
            {
                return this.channelTypeField;
            }
            set
            {
                this.channelTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string ChannelDescription
        {
            get
            {
                return this.channelDescriptionField;
            }
            set
            {
                this.channelDescriptionField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetChannels", WrapperNamespace = "http://www.openoandm.org/ws-isbm/", IsWrapped = true)]
    public partial class GetChannelsRequest
    {

        public GetChannelsRequest()
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetChannelsResponse", WrapperNamespace = "http://www.openoandm.org/ws-isbm/", IsWrapped = true)]
    public partial class GetChannelsResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openoandm.org/ws-isbm/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("Channel")]
        public Channel[] Channel;

        public GetChannelsResponse()
        {
        }

        public GetChannelsResponse(Channel[] Channel)
        {
            this.Channel = Channel;
        }
    }
}

namespace www.openoandm.org.wsisbm
{
    using System.Runtime.Serialization;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ChannelType", Namespace = "http://www.openoandm.org/ws-isbm/")]
    public enum ChannelType : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Publication = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Request = 1,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ChannelFault", Namespace = "http://www.openoandm.org/ws-isbm/")]
    public class ChannelFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SecurityTokenFault", Namespace = "http://www.openoandm.org/ws-isbm/")]
    public partial class SecurityTokenFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
}
