//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://www.openoandm.org/ws-isbm/", ClrNamespace = "www.openoandm.org.wsisbm")]
namespace OpenMSM.Web.ServiceDefinitions
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.openoandm.org/ws-isbm/", ConfigurationName = "ConsumerRequestService")]
    public interface IConsumerRequestService
    {
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/OpenConsumerRequestSession", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(www.openoandm.org.wsisbm.ChannelFault), Action = "http://www.openoandm.org/ws-isbm/OpenConsumerRequestSession", Name = "ChannelFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(www.openoandm.org.wsisbm.OperationFault), Action = "http://www.openoandm.org/ws-isbm/OpenConsumerRequestSession", Name = "OperationFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "SessionID")]
        string OpenConsumerRequestSession(string ChannelURI, string ListenerURL);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/OpenConsumerRequestSession", ReplyAction = "*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "SessionID")]
        System.Threading.Tasks.Task<string> OpenConsumerRequestSessionAsync(string ChannelURI, string ListenerURL);

        // CODEGEN: Parameter 'Expiry' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/PostRequest", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(www.openoandm.org.wsisbm.SessionFault), Action = "http://www.openoandm.org/ws-isbm/PostRequest", Name = "SessionFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "MessageID")]
        PostRequestResponse PostRequest(PostRequestRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/PostRequest", ReplyAction = "*")]
        System.Threading.Tasks.Task<PostRequestResponse> PostRequestAsync(PostRequestRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/ExpireRequest", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(www.openoandm.org.wsisbm.SessionFault), Action = "http://www.openoandm.org/ws-isbm/ExpireRequest", Name = "SessionFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void ExpireRequest(string SessionID, string MessageID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/ExpireRequest", ReplyAction = "*")]
        System.Threading.Tasks.Task ExpireRequestAsync(string SessionID, string MessageID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/ReadResponse", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(www.openoandm.org.wsisbm.SessionFault), Action = "http://www.openoandm.org/ws-isbm/ReadResponse", Name = "SessionFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "ResponseMessage")]
        ResponseMessage ReadResponse(string SessionID, string RequestMessageID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/ReadResponse", ReplyAction = "*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "ResponseMessage")]
        System.Threading.Tasks.Task<ResponseMessage> ReadResponseAsync(string SessionID, string RequestMessageID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/RemoveResponse", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(www.openoandm.org.wsisbm.SessionFault), Action = "http://www.openoandm.org/ws-isbm/RemoveResponse", Name = "SessionFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void RemoveResponse(string SessionID, string RequestMessageID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/RemoveResponse", ReplyAction = "*")]
        System.Threading.Tasks.Task RemoveResponseAsync(string SessionID, string RequestMessageID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/CloseConsumerRequestSession", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(www.openoandm.org.wsisbm.SessionFault), Action = "http://www.openoandm.org/ws-isbm/CloseConsumerRequestSession", Name = "SessionFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void CloseConsumerRequestSession(string SessionID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/CloseConsumerRequestSession", ReplyAction = "*")]
        System.Threading.Tasks.Task CloseConsumerRequestSessionAsync(string SessionID);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "PostRequest", WrapperNamespace = "http://www.openoandm.org/ws-isbm/", IsWrapped = true)]
    public partial class PostRequestRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openoandm.org/ws-isbm/", Order = 0)]
        public string SessionID;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openoandm.org/ws-isbm/", Order = 1)]
        public MessageContent MessageContent;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openoandm.org/ws-isbm/", Order = 2)]
        public string Topic;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openoandm.org/ws-isbm/", Order = 3)]
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        public string Expiry;

        public PostRequestRequest()
        {
        }

        public PostRequestRequest(string SessionID, MessageContent MessageContent, string Topic, string Expiry)
        {
            this.SessionID = SessionID;
            this.MessageContent = MessageContent;
            this.Topic = Topic;
            this.Expiry = Expiry;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "PostRequestResponse", WrapperNamespace = "http://www.openoandm.org/ws-isbm/", IsWrapped = true)]
    public partial class PostRequestResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openoandm.org/ws-isbm/", Order = 0)]
        public string MessageID;

        public PostRequestResponse()
        {
        }

        public PostRequestResponse(string MessageID)
        {
            this.MessageID = MessageID;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.openoandm.org/ws-isbm/")]
    public partial class ResponseMessage
    {

        private string messageIDField;

        private MessageContent messageContentField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string MessageID
        {
            get
            {
                return this.messageIDField;
            }
            set
            {
                this.messageIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public MessageContent MessageContent
        {
            get
            {
                return this.messageContentField;
            }
            set
            {
                this.messageContentField = value;
            }
        }
    }
}
namespace www.openoandm.org.wsisbm
{
    using System.Runtime.Serialization;
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SessionFault", Namespace = "http://www.openoandm.org/ws-isbm/")]
    public partial class SessionFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
}
