//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://www.openoandm.org/ws-isbm/", ClrNamespace = "www.openoandm.org.wsisbm")]
namespace OpenMSM.Web.ServiceDefinitions
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.openoandm.org/ws-isbm/", ConfigurationName = "ConsumerPublicationService")]
    public interface IConsumerPublicationService
    {

        // CODEGEN: Parameter 'Topic' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/OpenSubscriptionSession", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(www.openoandm.org.wsisbm.ChannelFault), Action = "http://www.openoandm.org/ws-isbm/OpenSubscriptionSession", Name = "ChannelFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(www.openoandm.org.wsisbm.NamespaceFault), Action = "http://www.openoandm.org/ws-isbm/OpenSubscriptionSession", Name = "NamespaceFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(www.openoandm.org.wsisbm.OperationFault), Action = "http://www.openoandm.org/ws-isbm/OpenSubscriptionSession", Name = "OperationFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "SessionID")]
        OpenSubscriptionSessionResponse OpenSubscriptionSession(OpenSubscriptionSessionRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/OpenSubscriptionSession", ReplyAction = "*")]
        System.Threading.Tasks.Task<OpenSubscriptionSessionResponse> OpenSubscriptionSessionAsync(OpenSubscriptionSessionRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/ReadPublication", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(www.openoandm.org.wsisbm.SessionFault), Action = "http://www.openoandm.org/ws-isbm/ReadPublication", Name = "SessionFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "PublicationMessage")]
        PublicationMessage ReadPublication(string SessionID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/ReadPublication", ReplyAction = "*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "PublicationMessage")]
        System.Threading.Tasks.Task<PublicationMessage> ReadPublicationAsync(string SessionID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/ReadPublication", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(www.openoandm.org.wsisbm.SessionFault), Action = "http://www.openoandm.org/ws-isbm/ReadPublication", Name = "SessionFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void RemovePublication(string SessionID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/ReadPublication", ReplyAction = "*")]
        System.Threading.Tasks.Task RemovePublicationAsync(string SessionID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/CloseSubscriptionSession", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(www.openoandm.org.wsisbm.SessionFault), Action = "http://www.openoandm.org/ws-isbm/CloseSubscriptionSession", Name = "SessionFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void CloseSubscriptionSession(string SessionID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/CloseSubscriptionSession", ReplyAction = "*")]
        System.Threading.Tasks.Task CloseSubscriptionSessionAsync(string SessionID);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.openoandm.org/ws-isbm/")]
    public partial class PublicationMessage
    {

        private string messageIDField;

        private System.Xml.XmlElement messageContentField;

        private string[] topicField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string MessageID
        {
            get
            {
                return this.messageIDField;
            }
            set
            {
                this.messageIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public System.Xml.XmlElement MessageContent
        {
            get
            {
                return this.messageContentField;
            }
            set
            {
                this.messageContentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Topic", Order = 2)]
        public string[] Topic
        {
            get
            {
                return this.topicField;
            }
            set
            {
                this.topicField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "OpenSubscriptionSession", WrapperNamespace = "http://www.openoandm.org/ws-isbm/", IsWrapped = true)]
    public partial class OpenSubscriptionSessionRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openoandm.org/ws-isbm/", Order = 0)]
        public string ChannelURI;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openoandm.org/ws-isbm/", Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute("Topic")]
        public string[] Topic;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openoandm.org/ws-isbm/", Order = 2)]
        public string ListenerURL;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openoandm.org/ws-isbm/", Order = 3)]
        public string XPathExpression;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openoandm.org/ws-isbm/", Order = 4)]
        [System.Xml.Serialization.XmlElementAttribute("XPathNamespace")]
        public Namespace[] XPathNamespace;

        public OpenSubscriptionSessionRequest()
        {
        }

        public OpenSubscriptionSessionRequest(string ChannelURI, string[] Topic, string ListenerURL, string XPathExpression, Namespace[] XPathNamespace)
        {
            this.ChannelURI = ChannelURI;
            this.Topic = Topic;
            this.ListenerURL = ListenerURL;
            this.XPathExpression = XPathExpression;
            this.XPathNamespace = XPathNamespace;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "OpenSubscriptionSessionResponse", WrapperNamespace = "http://www.openoandm.org/ws-isbm/", IsWrapped = true)]
    public partial class OpenSubscriptionSessionResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openoandm.org/ws-isbm/", Order = 0)]
        public string SessionID;

        public OpenSubscriptionSessionResponse()
        {
        }

        public OpenSubscriptionSessionResponse(string SessionID)
        {
            this.SessionID = SessionID;
        }
    }
}
