//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://www.openoandm.org/ws-isbm/", ClrNamespace="www.openoandm.org.wsisbm")]

namespace OpenMSM.Web.ServiceDefinitions
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.openoandm.org/ws-isbm/", ConfigurationName = "ProviderRequestService")]
    public interface IProviderRequestService
    {

        // CODEGEN: Parameter 'Topic' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/OpenProviderRequestSession", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(www.openoandm.org.wsisbm.ChannelFault), Action = "http://www.openoandm.org/ws-isbm/OpenProviderRequestSession", Name = "ChannelFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(www.openoandm.org.wsisbm.NamespaceFault), Action = "http://www.openoandm.org/ws-isbm/OpenProviderRequestSession", Name = "NamespaceFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(www.openoandm.org.wsisbm.OperationFault), Action = "http://www.openoandm.org/ws-isbm/OpenProviderRequestSession", Name = "OperationFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "SessionID")]
        OpenProviderRequestSessionResponse OpenProviderRequestSession(OpenProviderRequestSessionRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/OpenProviderRequestSession", ReplyAction = "*")]
        System.Threading.Tasks.Task<OpenProviderRequestSessionResponse> OpenProviderRequestSessionAsync(OpenProviderRequestSessionRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/ReadRequest", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(www.openoandm.org.wsisbm.SessionFault), Action = "http://www.openoandm.org/ws-isbm/ReadRequest", Name = "SessionFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "RequestMessage")]
        RequestMessage ReadRequest(string SessionID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/ReadRequest", ReplyAction = "*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "RequestMessage")]
        System.Threading.Tasks.Task<RequestMessage> ReadRequestAsync(string SessionID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/RemoveRequest", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(www.openoandm.org.wsisbm.SessionFault), Action = "http://www.openoandm.org/ws-isbm/RemoveRequest", Name = "SessionFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void RemoveRequest(string SessionID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/RemoveRequest", ReplyAction = "*")]
        System.Threading.Tasks.Task RemoveRequestAsync(string SessionID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/PostResponse", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(www.openoandm.org.wsisbm.SessionFault), Action = "http://www.openoandm.org/ws-isbm/PostResponse", Name = "SessionFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "MessageID")]
        string PostResponse(string SessionID, string RequestMessageID, MessageContent MessageContent);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/PostResponse", ReplyAction = "*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "MessageID")]
        System.Threading.Tasks.Task<string> PostResponseAsync(string SessionID, string RequestMessageID, MessageContent MessageContent);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/CloseProviderRequestSession", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(www.openoandm.org.wsisbm.SessionFault), Action = "http://www.openoandm.org/ws-isbm/CloseProviderRequestSession", Name = "SessionFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void CloseProviderRequestSession(string SessionID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.openoandm.org/ws-isbm/CloseProviderRequestSession", ReplyAction = "*")]
        System.Threading.Tasks.Task CloseProviderRequestSessionAsync(string SessionID);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.openoandm.org/ws-isbm/")]
    public partial class Namespace
    {

        private string namespacePrefixField;

        private string namespaceNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string NamespacePrefix
        {
            get
            {
                return this.namespacePrefixField;
            }
            set
            {
                this.namespacePrefixField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string NamespaceName
        {
            get
            {
                return this.namespaceNameField;
            }
            set
            {
                this.namespaceNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.openoandm.org/ws-isbm/")]
    public partial class RequestMessage
    {

        private string messageIDField;

        private MessageContent messageContentField;

        private string topicField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string MessageID
        {
            get
            {
                return this.messageIDField;
            }
            set
            {
                this.messageIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public MessageContent MessageContent
        {
            get
            {
                return this.messageContentField;
            }
            set
            {
                this.messageContentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string Topic
        {
            get
            {
                return this.topicField;
            }
            set
            {
                this.topicField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "OpenProviderRequestSession", WrapperNamespace = "http://www.openoandm.org/ws-isbm/", IsWrapped = true)]
    public partial class OpenProviderRequestSessionRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openoandm.org/ws-isbm/", Order = 0)]
        public string ChannelURI;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openoandm.org/ws-isbm/", Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute("Topic")]
        public string[] Topic;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openoandm.org/ws-isbm/", Order = 2)]
        public string ListenerURL;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openoandm.org/ws-isbm/", Order = 3)]
        public string XPathExpression;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openoandm.org/ws-isbm/", Order = 4)]
        [System.Xml.Serialization.XmlElementAttribute("XPathNamespace")]
        public Namespace[] XPathNamespace;

        public OpenProviderRequestSessionRequest()
        {
        }

        public OpenProviderRequestSessionRequest(string ChannelURI, string[] Topic, string ListenerURL, string XPathExpression, Namespace[] XPathNamespace)
        {
            this.ChannelURI = ChannelURI;
            this.Topic = Topic;
            this.ListenerURL = ListenerURL;
            this.XPathExpression = XPathExpression;
            this.XPathNamespace = XPathNamespace;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "OpenProviderRequestSessionResponse", WrapperNamespace = "http://www.openoandm.org/ws-isbm/", IsWrapped = true)]
    public partial class OpenProviderRequestSessionResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.openoandm.org/ws-isbm/", Order = 0)]
        public string SessionID;

        public OpenProviderRequestSessionResponse()
        {
        }

        public OpenProviderRequestSessionResponse(string SessionID)
        {
            this.SessionID = SessionID;
        }
    }
}
namespace www.openoandm.org.wsisbm
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NamespaceFault", Namespace="http://www.openoandm.org/ws-isbm/")]
    public partial class NamespaceFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationFault", Namespace="http://www.openoandm.org/ws-isbm/")]
    public partial class OperationFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
}
