//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 
namespace OpenMSM.ServiceDefinitions
{
    public interface IConsumerRequestServiceSoap
    {
        string OpenConsumerRequestSession(string ChannelURI, string ListenerURL);
        string PostRequest(string SessionID, System.Xml.XmlElement MessageContent, string Topic, [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")] string Expiry);
        void ExpireRequest(string SessionID, string MessageID);

        ResponseMessage ReadResponse(string SessionID, string RequestMessageID);
        void RemoveResponse(string SessionID, string RequestMessageID);
        void CloseConsumerRequestSession(string SessionID);
    }

    public partial class ResponseMessage
    {
        private string messageIDField;
        private System.Xml.XmlElement messageContentField;

        public string MessageID
        {
            get
            {
                return this.messageIDField;
            }
            set
            {
                this.messageIDField = value;
            }
        }
        public System.Xml.XmlElement MessageContent
        {
            get
            {
                return this.messageContentField;
            }
            set
            {
                this.messageContentField = value;
            }
        }
    }
}
