//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 
namespace OpenMSM.ServiceDefinitions
{
    public interface IProviderRequestServiceSoap {
        
        string OpenProviderRequestSession(string ChannelURI, [System.Xml.Serialization.XmlElementAttribute("Topic")] string[] Topic, string ListenerURL, string XPathExpression, [System.Xml.Serialization.XmlElementAttribute("XPathNamespace")] Namespace[] XPathNamespace);
        
        RequestMessage ReadRequest(string SessionID);
        
        void RemoveRequest(string SessionID);
        
        string PostResponse(string SessionID, string RequestMessageID, System.Xml.XmlElement MessageContent);
        
        void CloseProviderRequestSession(string SessionID);
    }
    
    public partial class RequestMessage {
        
        private string messageIDField;
        
        private System.Xml.XmlElement messageContentField;
        
        private string topicField;
        
        public string MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        public System.Xml.XmlElement MessageContent {
            get {
                return this.messageContentField;
            }
            set {
                this.messageContentField = value;
            }
        }
        
        public string Topic {
            get {
                return this.topicField;
            }
            set {
                this.topicField = value;
            }
        }
    }
}
