//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 
namespace ISBM.ServiceDefinitions
{
    public interface IChannelManagementServiceSoap
    {
        void CreateChannel(string ChannelURI, ChannelType ChannelType, string ChannelDescription, [System.Xml.Serialization.XmlElementAttribute("SecurityToken")] System.Xml.XmlElement[] SecurityToken);
        void AddSecurityTokens(string ChannelURI, [System.Xml.Serialization.XmlElementAttribute("SecurityToken")] System.Xml.XmlElement[] SecurityToken);
        void RemoveSecurityTokens(string ChannelURI, [System.Xml.Serialization.XmlElementAttribute("SecurityToken")] System.Xml.XmlElement[] SecurityToken);
        void DeleteChannel(string ChannelURI);
        Channel GetChannel(string ChannelURI);
        Channel[] GetChannels();
    }

    public enum ChannelType
    {
        Publication,
        Request,
    }

    public partial class Channel
    {
        private string channelURIField;
        private ChannelType channelTypeField;
        private string channelDescriptionField;

        public string ChannelURI
        {
            get
            {
                return this.channelURIField;
            }
            set
            {
                this.channelURIField = value;
            }
        }

        public ChannelType ChannelType
        {
            get
            {
                return this.channelTypeField;
            }
            set
            {
                this.channelTypeField = value;
            }
        }

        public string ChannelDescription
        {
            get
            {
                return this.channelDescriptionField;
            }
            set
            {
                this.channelDescriptionField = value;
            }
        }
    }
}
