//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 
namespace ISBM.ServiceDefinitions {
    
    
    public interface IConsumerPublicationServiceSoap {
        string OpenSubscriptionSession(string ChannelURI, [System.Xml.Serialization.XmlElementAttribute("Topic")] string[] Topic, string ListenerURL, string XPathExpression, [System.Xml.Serialization.XmlElementAttribute("XPathNamespace")] Namespace[] XPathNamespace);
        PublicationMessage ReadPublication(string SessionID);
        void RemovePublication(string SessionID);
        void CloseSubscriptionSession(string SessionID);
    }
    
    public partial class Namespace {
        
        private string namespacePrefixField;
        
        private string namespaceNameField;
        
        public string NamespacePrefix {
            get {
                return this.namespacePrefixField;
            }
            set {
                this.namespacePrefixField = value;
            }
        }
        
        public string NamespaceName {
            get {
                return this.namespaceNameField;
            }
            set {
                this.namespaceNameField = value;
            }
        }
    }
    
    public partial class PublicationMessage {
        
        private string messageIDField;
        
        private System.Xml.XmlElement messageContentField;
        
        private string[] topicField;
        
        public string MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        public System.Xml.XmlElement MessageContent {
            get {
                return this.messageContentField;
            }
            set {
                this.messageContentField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Topic")]
        public string[] Topic {
            get {
                return this.topicField;
            }
            set {
                this.topicField = value;
            }
        }
    }
}
